### PR TITLE
Simple Matrix class

### PR DESCRIPTION
**Pull request by blsemo**
Provide a simple matrix class for these use cases where a matrix with a fixed number of columns and rows is required - really just a 2d array, but more expressive and safer than a vector of vectors, and easier than rolling it out and having the index arithmetic in the business logic.

### CODE REVIEW

**Comment by orange-vertex** [comment]
Also, maybe we need a clear() function as well?

**Comment by blsemo** [comment]
What would you expect the clear function to do? It's not like the array can be resized, and resetting all elements depends on what they actually are.

On 11 October 2018 01:40:49 BST, Petros Koutsolampros <notifications@github.com> wrote:
>Also, maybe we need a clear() function as well?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SpaceGroupUCL/depthmapX/pull/247#issuecomment-428778783

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by orange-vertex** [comment]
Not idea really, just asking because the previous implementations ([pvecint **m_pixel_lines](https://github.com/SpaceGroupUCL/depthmapX/commit/725c0029a53a37077362cad2efc008969e05102b#diff-8cd09019438742bbd9c855ad56d79d7dL109)) got [set to NULL](https://github.com/SpaceGroupUCL/depthmapX/commit/725c0029a53a37077362cad2efc008969e05102b#diff-4bdae2d07f81e81d5ba188626be5b3e3L355) all the time. I suppose in this implementation we just replace them with new ones?

**Comment by blsemo** [comment]
I have added an initialiseValues function and a reset function that can be used to change the underlying storage for a given matrix, thus discarding any content. To completely get rid of the storage overhead if a matrix is not in use, do `matrix.reset(0,0);`, and then `matrix.reset(rows, cols)` when it is required again. However, in this case, just getting rid of the matrix and creating a new one when it's need would have about the same overhead.

**Comment by blsemo** [comment]
The checks did actually pass on travis, but github didn't pick up the completion. Merged anyway.

**Pull request merged**
