### PR TITLE
Map opengl

### PR DESCRIPTION
**Pull request by orange-vertex**
Display datamaps, the grid and various other fixes

### CODE REVIEW

**Comment by varoudis** [comment]
send me an OSX build to test please

**Comment by orange-vertex** [comment]
See here: https://github.com/orange-vertex/depthmapX/blob/84601b6741117fd676148781f2801455d5ce79e8/dist/beta/map_opengl/darwin/depthmapX.zip?raw=true

**Comment by orange-vertex** [comment]
New commits should fix the issue at least on macos. They also fix the other macos drawing problems as mentioned in issue https://github.com/SpaceGroupUCL/depthmapX/issues/36

(See current build here: https://github.com/orange-vertex/depthmapX/blob/b1ee552663fc9ccb473046e543ec6231d93000b7/dist/beta/map_opengl/macos/depthmapX.zip?raw=true)

**Comment by varoudis** [comment]
if original drawing is ok on mac thats great!
ill test in a couple of days. Im on transit now.

**Pull request merged**
